language: python
python:
  - "3.5"
  - "3.6"
os:
  - linux
dist: trusty
notifications:
  email: false
before_install:
  - sudo apt-get update
  - sudo apt-get install -y checkinstall build-essential
  - sudo apt-get install portaudio19-dev
  - sudo apt-get install libsecret-1-dev
  - sudo apt install python3-pyqt5
  - sudo apt-get install libconfig-dev libvpx-dev check -qq
install:
  - pip install sip
  - pip install pyaudio
  - pip install opencv-python
before_script:
# Opus
  - wget http://downloads.xiph.org/releases/opus/opus-1.0.3.tar.gz
  - tar xzf opus-1.0.3.tar.gz
  - cd opus-1.0.3
  - ./configure
  - make -j3
  - sudo make install
  - cd ..
# Libsodium
  - git clone git://github.com/jedisct1/libsodium.git
  - cd libsodium
  - git checkout tags/1.0.3
  - ./autogen.sh
  - ./configure && make -j$(nproc)
  - sudo checkinstall --install --pkgname libsodium --pkgversion 1.0.0 --nodoc -y
  - sudo ldconfig
  - cd ..
# Toxcore
  - git clone https://github.com/irungentoo/toxcore.git
  - cd toxcore
  - autoreconf -if
  - ./configure
  - make -j$(nproc)
  - sudo make install
  - echo '/usr/local/lib/' | sudo tee -a /etc/ld.so.conf.d/locallib.conf
  - sudo ldconfig
  - cd ..
script:
  - py.test tests/travis.py
  - py.test tests/tests.py
